# Generated by Django 5.2.1 on 2025-05-23 19:50

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appliance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appliance_type",
                    models.CharField(
                        choices=[
                            ("ac", "Air Conditioner"),
                            ("refrigerator", "Refrigerator"),
                            ("washing_machine", "Washing Machine"),
                            ("microwave", "Microwave"),
                            ("dishwasher", "Dishwasher"),
                            ("water_heater", "Water Heater"),
                            ("tv", "Television"),
                            ("fan", "Ceiling Fan"),
                            ("light", "Light Fixture"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("brand", models.CharField(blank=True, max_length=100)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("age_years", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("new", "New"),
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                        ],
                        max_length=20,
                    ),
                ),
                ("warranty_status", models.BooleanField(default=False)),
                ("warranty_expires", models.DateField(blank=True, null=True)),
                ("specifications", models.JSONField(blank=True, default=dict)),
                ("energy_rating", models.CharField(blank=True, max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "property_appliances",
            },
        ),
        migrations.CreateModel(
            name="BuildingMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "component",
                    models.CharField(
                        choices=[
                            ("foundation", "Foundation"),
                            ("structure", "Structure"),
                            ("walls", "Walls"),
                            ("roof", "Roof"),
                            ("flooring", "Flooring"),
                            ("doors", "Doors"),
                            ("windows", "Windows"),
                            ("plumbing", "Plumbing"),
                            ("electrical", "Electrical"),
                            ("paint", "Paint/Finish"),
                        ],
                        max_length=50,
                    ),
                ),
                ("material_type", models.CharField(max_length=100)),
                ("brand", models.CharField(blank=True, max_length=100)),
                (
                    "quality_score",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "Poor"),
                            (2, "Below Average"),
                            (3, "Average"),
                            (4, "Good"),
                            (5, "Excellent"),
                        ]
                    ),
                ),
                ("installation_date", models.DateField(blank=True, null=True)),
                ("warranty_period", models.PositiveIntegerField(blank=True, null=True)),
                ("maintenance_notes", models.TextField(blank=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "building_materials",
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True)),
                ("description", models.TextField()),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("apartment", "Apartment"),
                            ("house", "Independent House"),
                            ("villa", "Villa"),
                            ("studio", "Studio Apartment"),
                            ("penthouse", "Penthouse"),
                            ("duplex", "Duplex"),
                            ("commercial", "Commercial Space"),
                            ("office", "Office Space"),
                            ("retail", "Retail Space"),
                            ("warehouse", "Warehouse"),
                            ("land", "Plot/Land"),
                            ("farmhouse", "Farmhouse"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "listing_type",
                    models.CharField(
                        choices=[
                            ("sale", "For Sale"),
                            ("rent", "For Rent"),
                            ("pg", "Paying Guest"),
                            ("lease", "Lease"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("sold", "Sold"),
                            ("rented", "Rented"),
                            ("under_offer", "Under Offer"),
                            ("off_market", "Off Market"),
                            ("coming_soon", "Coming Soon"),
                        ],
                        db_index=True,
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        db_index=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        db_index=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                    ),
                ),
                ("address", models.TextField()),
                ("locality", models.CharField(db_index=True, max_length=100)),
                ("city", models.CharField(db_index=True, max_length=100)),
                ("state", models.CharField(db_index=True, max_length=100)),
                ("country", models.CharField(default="India", max_length=100)),
                ("pincode", models.CharField(db_index=True, max_length=10)),
                (
                    "price",
                    models.DecimalField(db_index=True, decimal_places=2, max_digits=15),
                ),
                (
                    "price_per_sqft",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "maintenance_charges",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "security_deposit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("total_area", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "carpet_area",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "built_up_area",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "super_area",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "bedrooms",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(20)]
                    ),
                ),
                (
                    "bathrooms",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(20)]
                    ),
                ),
                (
                    "balconies",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(10)],
                    ),
                ),
                ("total_floors", models.PositiveIntegerField(blank=True, null=True)),
                ("floor_number", models.PositiveIntegerField(blank=True, null=True)),
                ("year_built", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "property_age",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("under_construction", "Under Construction"),
                            ("ready_to_move", "Ready to Move"),
                            ("1-2_years", "1-2 Years"),
                            ("3-5_years", "3-5 Years"),
                            ("5-10_years", "5-10 Years"),
                            ("10+_years", "10+ Years"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "furnishing_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("unfurnished", "Unfurnished"),
                            ("semi_furnished", "Semi Furnished"),
                            ("fully_furnished", "Fully Furnished"),
                        ],
                        max_length=20,
                    ),
                ),
                ("parking_spaces", models.PositiveIntegerField(default=0)),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Property features like AC, Lift, etc.",
                    ),
                ),
                (
                    "amenities",
                    models.JSONField(
                        blank=True, default=list, help_text="Building/Society amenities"
                    ),
                ),
                ("smart_home_features", models.JSONField(blank=True, default=list)),
                ("accessibility_features", models.JSONField(blank=True, default=list)),
                (
                    "energy_rating",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("solar_panels", models.BooleanField(default=False)),
                ("rera_id", models.CharField(blank=True, max_length=50, null=True)),
                ("legal_clearance", models.JSONField(blank=True, default=dict)),
                ("is_verified", models.BooleanField(default=False)),
                ("verification_date", models.DateTimeField(blank=True, null=True)),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("likes_count", models.PositiveIntegerField(default=0)),
                ("inquiries_count", models.PositiveIntegerField(default=0)),
                ("meta_title", models.CharField(blank=True, max_length=200)),
                ("meta_description", models.TextField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("featured_until", models.DateTimeField(blank=True, null=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_premium", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "properties",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inquiry_type",
                    models.CharField(
                        choices=[
                            ("general", "General Inquiry"),
                            ("visit", "Schedule Visit"),
                            ("price", "Price Negotiation"),
                            ("finance", "Financing Options"),
                            ("legal", "Legal Documentation"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("contact_phone", models.CharField(blank=True, max_length=15)),
                (
                    "preferred_contact_time",
                    models.CharField(blank=True, max_length=100),
                ),
                ("is_responded", models.BooleanField(default=False)),
                ("response_message", models.TextField(blank=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "property_inquiries",
            },
        ),
        migrations.CreateModel(
            name="PropertyLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "property_likes",
            },
        ),
        migrations.CreateModel(
            name="PropertyMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("photo", "Photo"),
                            ("video", "Video"),
                            ("360_tour", "360° Tour"),
                            ("floor_plan", "Floor Plan"),
                            ("document", "Document"),
                            ("virtual_tour", "Virtual Tour"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="property_media/")),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="property_thumbnails/"
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("alt_text", models.CharField(blank=True, max_length=200)),
                ("file_size", models.PositiveIntegerField(blank=True, null=True)),
                ("dimensions", models.JSONField(blank=True, default=dict)),
                ("duration", models.PositiveIntegerField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_primary", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "property_media",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("referrer", models.URLField(blank=True, null=True)),
                ("session_key", models.CharField(blank=True, max_length=40)),
                ("device_info", models.JSONField(blank=True, default=dict)),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                ("time_spent", models.PositiveIntegerField(default=0)),
                ("interactions", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "property_views",
            },
        ),
    ]
