# Generated by Django 5.2.1 on 2025-05-23 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_properties",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_properties",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_properties",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="buildingmaterial",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="building_materials",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="appliance",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appliances",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="propertyinquiry",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inquiries",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="propertyinquiry",
            name="responded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="responded_inquiries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="propertyinquiry",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="propertylike",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="propertylike",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="propertymedia",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="propertyview",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property_views",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="propertyview",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["property_type", "listing_type"],
                name="properties_propert_406856_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["city", "locality"], name="properties_city_4313d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(fields=["price"], name="properties_price_aa33af_idx"),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["bedrooms", "bathrooms"], name="properties_bedroom_2aae3d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["latitude", "longitude"], name="properties_latitud_5ee5e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["status", "is_active"], name="properties_status_8d5710_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["-created_at"], name="properties_created_2ede73_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="buildingmaterial",
            unique_together={("property", "component")},
        ),
        migrations.AddIndex(
            model_name="propertyinquiry",
            index=models.Index(
                fields=["property"], name="property_in_propert_552d39_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propertyinquiry",
            index=models.Index(fields=["user"], name="property_in_user_id_61e4d0_idx"),
        ),
        migrations.AddIndex(
            model_name="propertyinquiry",
            index=models.Index(
                fields=["is_responded"], name="property_in_is_resp_40e436_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propertylike",
            index=models.Index(fields=["user"], name="property_li_user_id_4cbe7a_idx"),
        ),
        migrations.AddIndex(
            model_name="propertylike",
            index=models.Index(
                fields=["property"], name="property_li_propert_8f5aba_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="propertylike",
            unique_together={("user", "property")},
        ),
        migrations.AddIndex(
            model_name="propertymedia",
            index=models.Index(
                fields=["property", "media_type"], name="property_me_propert_b10429_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propertymedia",
            index=models.Index(
                fields=["is_primary"], name="property_me_is_prim_a31b3c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propertyview",
            index=models.Index(
                fields=["property"], name="property_vi_propert_c2fc16_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propertyview",
            index=models.Index(fields=["user"], name="property_vi_user_id_e862d3_idx"),
        ),
        migrations.AddIndex(
            model_name="propertyview",
            index=models.Index(
                fields=["viewed_at"], name="property_vi_viewed__6309c1_idx"
            ),
        ),
    ]
