# Generated by Django 5.2.1 on 2025-05-23 20:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationTrend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_name", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "average_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "price_per_sqft",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("price_trend", models.FloatField(default=0.0)),
                ("search_volume", models.PositiveIntegerField(default=0)),
                ("property_count", models.PositiveIntegerField(default=0)),
                ("active_listings", models.PositiveIntegerField(default=0)),
                ("trend_score", models.FloatField(default=0.0)),
                ("is_trending_up", models.BooleanField(default=False)),
                ("is_hot_location", models.BooleanField(default=False)),
                ("data_date", models.DateField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "location_trends",
                "ordering": ["-trend_score", "-search_volume"],
                "indexes": [
                    models.Index(
                        fields=["city", "trend_score"],
                        name="location_tr_city_2cfc4d_idx",
                    ),
                    models.Index(
                        fields=["is_trending_up"], name="location_tr_is_tren_aefe2a_idx"
                    ),
                    models.Index(
                        fields=["data_date"], name="location_tr_data_da_8e6f17_idx"
                    ),
                ],
                "unique_together": {("location_name", "city", "data_date")},
            },
        ),
        migrations.CreateModel(
            name="PopularSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("search_term", models.CharField(max_length=200, unique=True)),
                (
                    "search_type",
                    models.CharField(
                        choices=[
                            ("property", "Property Search"),
                            ("agent", "Agent Search"),
                            ("location", "Location Search"),
                        ],
                        default="property",
                        max_length=20,
                    ),
                ),
                ("search_count", models.PositiveIntegerField(default=1)),
                ("unique_users_count", models.PositiveIntegerField(default=1)),
                ("this_week_count", models.PositiveIntegerField(default=0)),
                ("this_month_count", models.PositiveIntegerField(default=0)),
                ("trending_score", models.FloatField(default=0.0)),
                ("is_trending", models.BooleanField(default=False)),
                ("associated_locations", models.JSONField(default=list)),
                ("average_price_range", models.JSONField(default=dict)),
                ("first_searched", models.DateTimeField(auto_now_add=True)),
                ("last_searched", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "popular_searches",
                "ordering": ["-trending_score", "-search_count"],
                "indexes": [
                    models.Index(
                        fields=["search_type", "trending_score"],
                        name="popular_sea_search__be86aa_idx",
                    ),
                    models.Index(
                        fields=["is_trending"], name="popular_sea_is_tren_223be2_idx"
                    ),
                    models.Index(
                        fields=["search_count"], name="popular_sea_search__0d6baf_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SearchSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200, unique=True)),
                (
                    "suggestion_type",
                    models.CharField(
                        choices=[
                            ("location", "Location"),
                            ("property_type", "Property Type"),
                            ("amenity", "Amenity"),
                            ("landmark", "Landmark"),
                            ("builder", "Builder"),
                            ("general", "General"),
                        ],
                        max_length=20,
                    ),
                ),
                ("popularity_score", models.FloatField(default=0.0)),
                ("click_count", models.PositiveIntegerField(default=0)),
                ("search_count", models.PositiveIntegerField(default=0)),
                ("associated_locations", models.JSONField(default=list)),
                ("metadata", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "search_suggestions",
                "ordering": ["-popularity_score", "-click_count"],
                "indexes": [
                    models.Index(
                        fields=["suggestion_type", "popularity_score"],
                        name="search_sugg_suggest_da41d5_idx",
                    ),
                    models.Index(
                        fields=["is_active", "is_verified"],
                        name="search_sugg_is_acti_c11b7e_idx",
                    ),
                    models.Index(fields=["text"], name="search_sugg_text_6052f9_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SavedSearch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "search_type",
                    models.CharField(
                        choices=[
                            ("property", "Property Search"),
                            ("agent", "Agent Search"),
                            ("location", "Location Search"),
                        ],
                        default="property",
                        max_length=20,
                    ),
                ),
                ("search_query", models.TextField(blank=True)),
                ("search_filters", models.JSONField(default=dict)),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("radius", models.PositiveIntegerField(default=10)),
                ("email_notifications", models.BooleanField(default=True)),
                (
                    "notification_frequency",
                    models.CharField(
                        choices=[
                            ("instant", "Instant"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("disabled", "Disabled"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                ("last_notification_sent", models.DateTimeField(blank=True, null=True)),
                ("search_count", models.PositiveIntegerField(default=0)),
                ("last_searched", models.DateTimeField(blank=True, null=True)),
                ("total_results_found", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "saved_searches",
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="saved_searc_user_id_2b1034_idx",
                    ),
                    models.Index(
                        fields=["search_type"], name="saved_searc_search__fc3a22_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="saved_searc_created_84d535_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SearchAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_id", models.CharField(blank=True, max_length=50)),
                (
                    "search_type",
                    models.CharField(
                        choices=[
                            ("property", "Property Search"),
                            ("agent", "Agent Search"),
                            ("location", "Location Search"),
                        ],
                        max_length=20,
                    ),
                ),
                ("search_query", models.TextField(blank=True)),
                ("search_filters", models.JSONField(default=dict)),
                ("results_count", models.PositiveIntegerField(default=0)),
                ("clicked_results", models.JSONField(default=list)),
                ("search_duration", models.PositiveIntegerField(blank=True, null=True)),
                ("search_location", models.CharField(blank=True, max_length=200)),
                (
                    "user_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "user_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("device_type", models.CharField(blank=True, max_length=20)),
                (
                    "time_on_results_page",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("pages_viewed", models.PositiveIntegerField(default=1)),
                ("properties_viewed", models.JSONField(default=list)),
                ("properties_liked", models.JSONField(default=list)),
                ("properties_shared", models.JSONField(default=list)),
                ("inquiry_sent", models.BooleanField(default=False)),
                ("contact_made", models.BooleanField(default=False)),
                ("saved_search_created", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="search_analytics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "search_analytics",
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="search_anal_user_id_5f3483_idx",
                    ),
                    models.Index(
                        fields=["search_type"], name="search_anal_search__0007ab_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="search_anal_created_b2167e_idx"
                    ),
                    models.Index(
                        fields=["session_id"], name="search_anal_session_d8fc09_idx"
                    ),
                ],
            },
        ),
    ]
