# Generated by Django 5.2.1 on 2025-05-23 19:50

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PointOfInterest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("hospital", "Hospital/Clinic"),
                            ("mall", "Shopping Mall"),
                            ("market", "Market"),
                            ("park", "Park/Garden"),
                            ("gym", "Gym/Fitness Center"),
                            ("restaurant", "Restaurant"),
                            ("bank", "Bank/ATM"),
                            ("metro", "Metro Station"),
                            ("bus_stop", "Bus Stop"),
                            ("airport", "Airport"),
                            ("railway", "Railway Station"),
                            ("temple", "Temple/Religious Place"),
                            ("entertainment", "Entertainment"),
                            ("government", "Government Office"),
                            ("police", "Police Station"),
                            ("fire", "Fire Station"),
                            ("petrol", "Petrol Pump"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(db_index=True, decimal_places=6, max_digits=9),
                ),
                (
                    "longitude",
                    models.DecimalField(db_index=True, decimal_places=6, max_digits=9),
                ),
                ("address", models.TextField()),
                ("description", models.TextField(blank=True)),
                ("features", models.JSONField(blank=True, default=list)),
                ("phone_number", models.CharField(blank=True, max_length=15)),
                ("website", models.URLField(blank=True)),
                ("operating_hours", models.JSONField(blank=True, default=dict)),
                (
                    "rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("reviews_count", models.PositiveIntegerField(default=0)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "points_of_interest",
            },
        ),
        migrations.CreateModel(
            name="PropertyVisitReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visit_date", models.DateField()),
                ("visit_duration", models.PositiveIntegerField(blank=True, null=True)),
                ("visited_with_agent", models.BooleanField(default=False)),
                (
                    "overall_rating",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "condition_rating",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "location_rating",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("review_text", models.TextField()),
                ("pros", models.JSONField(blank=True, default=list)),
                ("cons", models.JSONField(blank=True, default=list)),
                ("actual_condition", models.TextField(blank=True)),
                ("differences_from_listing", models.TextField(blank=True)),
                ("would_recommend", models.BooleanField(default=True)),
                ("target_audience", models.CharField(blank=True, max_length=200)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "visit_proof",
                    models.FileField(blank=True, null=True, upload_to="visit_proofs/"),
                ),
                ("helpful_votes", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "property_visit_reviews",
            },
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                (
                    "latitude",
                    models.DecimalField(db_index=True, decimal_places=6, max_digits=9),
                ),
                (
                    "longitude",
                    models.DecimalField(db_index=True, decimal_places=6, max_digits=9),
                ),
                ("address", models.TextField()),
                (
                    "catchment_area_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Catchment area as JSON"
                    ),
                ),
                (
                    "school_type",
                    models.CharField(
                        choices=[
                            ("primary", "Primary School"),
                            ("secondary", "Secondary School"),
                            ("high_school", "High School"),
                            ("college", "College"),
                            ("university", "University"),
                            ("professional", "Professional Institute"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "board",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cbse", "CBSE"),
                            ("icse", "ICSE"),
                            ("state", "State Board"),
                            ("ib", "International Baccalaureate"),
                            ("cambridge", "Cambridge"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_government", models.BooleanField(default=False)),
                ("is_coeducational", models.BooleanField(default=True)),
                (
                    "overall_rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "academic_rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                (
                    "infrastructure_rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                (
                    "teacher_rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                (
                    "pass_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "average_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("facilities", models.JSONField(blank=True, default=list)),
                ("extracurricular", models.JSONField(blank=True, default=list)),
                ("website", models.URLField(blank=True)),
                ("phone_number", models.CharField(blank=True, max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "student_capacity",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "current_enrollment",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("annual_fees_range", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "schools",
            },
        ),
        migrations.CreateModel(
            name="TransportHub",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                (
                    "transport_type",
                    models.CharField(
                        choices=[
                            ("metro", "Metro Station"),
                            ("bus", "Bus Stop"),
                            ("railway", "Railway Station"),
                            ("airport", "Airport"),
                            ("taxi_stand", "Taxi Stand"),
                            ("auto_stand", "Auto Stand"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(db_index=True, decimal_places=6, max_digits=9),
                ),
                (
                    "longitude",
                    models.DecimalField(db_index=True, decimal_places=6, max_digits=9),
                ),
                ("address", models.TextField()),
                ("lines_served", models.JSONField(blank=True, default=list)),
                ("connections", models.JSONField(blank=True, default=list)),
                ("facilities", models.JSONField(blank=True, default=list)),
                ("accessibility_features", models.JSONField(blank=True, default=list)),
                ("daily_footfall", models.PositiveIntegerField(blank=True, null=True)),
                ("peak_hours", models.JSONField(blank=True, default=dict)),
                ("first_service", models.TimeField(blank=True, null=True)),
                ("last_service", models.TimeField(blank=True, null=True)),
                ("frequency", models.PositiveIntegerField(blank=True, null=True)),
                ("is_operational", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "transport_hubs",
            },
        ),
        migrations.CreateModel(
            name="CommuteRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("from_longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("to_latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("to_longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("to_location_name", models.CharField(max_length=200)),
                (
                    "transport_mode",
                    models.CharField(
                        choices=[
                            ("driving", "Driving"),
                            ("public_transport", "Public Transport"),
                            ("walking", "Walking"),
                            ("cycling", "Cycling"),
                            ("metro", "Metro"),
                            ("bus", "Bus"),
                        ],
                        max_length=20,
                    ),
                ),
                ("distance_km", models.DecimalField(decimal_places=2, max_digits=8)),
                ("duration_minutes", models.PositiveIntegerField()),
                ("duration_peak", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "duration_off_peak",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "cost_one_way",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "cost_monthly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "route_polyline_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Route polyline as JSON"
                    ),
                ),
                ("intermediate_stops", models.JSONField(blank=True, default=list)),
                (
                    "service_frequency",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "reliability_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "commute_routes",
                "indexes": [
                    models.Index(
                        fields=["from_latitude", "from_longitude"],
                        name="commute_rou_from_la_6b4262_idx",
                    ),
                    models.Index(
                        fields=["to_latitude", "to_longitude"],
                        name="commute_rou_to_lati_895d09_idx",
                    ),
                    models.Index(
                        fields=["transport_mode"], name="commute_rou_transpo_2c6119_idx"
                    ),
                    models.Index(
                        fields=["duration_minutes"],
                        name="commute_rou_duratio_887d11_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Neighborhood",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("slug", models.SlugField(max_length=250, unique=True)),
                (
                    "boundaries_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Polygon boundaries as JSON"
                    ),
                ),
                (
                    "center_latitude",
                    models.DecimalField(db_index=True, decimal_places=6, max_digits=9),
                ),
                (
                    "center_longitude",
                    models.DecimalField(db_index=True, decimal_places=6, max_digits=9),
                ),
                ("city", models.CharField(db_index=True, max_length=100)),
                ("state", models.CharField(db_index=True, max_length=100)),
                ("country", models.CharField(default="India", max_length=100)),
                ("pincode", models.CharField(db_index=True, max_length=10)),
                (
                    "neighborhood_type",
                    models.CharField(
                        choices=[
                            ("residential", "Residential"),
                            ("commercial", "Commercial"),
                            ("mixed", "Mixed Use"),
                            ("industrial", "Industrial"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "development_level",
                    models.CharField(
                        choices=[
                            ("developing", "Developing"),
                            ("developed", "Well Developed"),
                            ("premium", "Premium"),
                            ("luxury", "Luxury"),
                        ],
                        max_length=20,
                    ),
                ),
                ("population", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "area_sqkm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "population_density",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "average_property_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "price_growth_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "demographics",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Age groups, income levels, etc.",
                    ),
                ),
                ("amenities", models.JSONField(blank=True, default=list)),
                (
                    "connectivity",
                    models.JSONField(
                        blank=True, default=dict, help_text="Metro, bus, highways etc."
                    ),
                ),
                (
                    "safety_rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                (
                    "connectivity_rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                (
                    "lifestyle_rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                (
                    "environment_rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("highlights", models.JSONField(blank=True, default=list)),
                ("future_developments", models.JSONField(blank=True, default=list)),
                ("properties_count", models.PositiveIntegerField(default=0)),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "neighborhoods",
                "indexes": [
                    models.Index(
                        fields=["city", "state"], name="neighborhoo_city_e9cdac_idx"
                    ),
                    models.Index(
                        fields=["neighborhood_type"],
                        name="neighborhoo_neighbo_18a5d7_idx",
                    ),
                    models.Index(
                        fields=["center_latitude", "center_longitude"],
                        name="neighborhoo_center__350614_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NeighborhoodReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "overall_rating",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("aspect_ratings", models.JSONField(blank=True, default=dict)),
                ("title", models.CharField(max_length=200)),
                ("review_text", models.TextField()),
                ("pros", models.JSONField(blank=True, default=list)),
                ("cons", models.JSONField(blank=True, default=list)),
                ("is_verified", models.BooleanField(default=False)),
                ("residency_verified", models.BooleanField(default=False)),
                ("helpful_votes", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "neighborhood",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="locations.neighborhood",
                    ),
                ),
            ],
            options={
                "db_table": "neighborhood_reviews",
            },
        ),
    ]
