# Generated by Django 5.2.1 on 2025-05-23 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0001_initial"),
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="neighborhoodreview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="pointofinterest",
            name="neighborhood",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pois",
                to="locations.neighborhood",
            ),
        ),
        migrations.AddField(
            model_name="propertyvisitreview",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visit_reviews",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="propertyvisitreview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="neighborhood",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schools",
                to="locations.neighborhood",
            ),
        ),
        migrations.AddIndex(
            model_name="transporthub",
            index=models.Index(
                fields=["transport_type"], name="transport_h_transpo_f3a287_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transporthub",
            index=models.Index(
                fields=["latitude", "longitude"], name="transport_h_latitud_583648_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="neighborhoodreview",
            index=models.Index(
                fields=["neighborhood", "overall_rating"],
                name="neighborhoo_neighbo_0ce39b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="neighborhoodreview",
            index=models.Index(fields=["user"], name="neighborhoo_user_id_c632d5_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="neighborhoodreview",
            unique_together={("neighborhood", "user")},
        ),
        migrations.AddIndex(
            model_name="pointofinterest",
            index=models.Index(
                fields=["category"], name="points_of_i_categor_ce733b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pointofinterest",
            index=models.Index(
                fields=["latitude", "longitude"], name="points_of_i_latitud_8a0e00_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pointofinterest",
            index=models.Index(fields=["rating"], name="points_of_i_rating_8e15a8_idx"),
        ),
        migrations.AddIndex(
            model_name="propertyvisitreview",
            index=models.Index(
                fields=["property", "overall_rating"],
                name="property_vi_propert_c219a0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="propertyvisitreview",
            index=models.Index(fields=["user"], name="property_vi_user_id_fd6882_idx"),
        ),
        migrations.AddIndex(
            model_name="propertyvisitreview",
            index=models.Index(
                fields=["visit_date"], name="property_vi_visit_d_0a9e97_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="propertyvisitreview",
            unique_together={("property", "user", "visit_date")},
        ),
        migrations.AddIndex(
            model_name="school",
            index=models.Index(
                fields=["school_type"], name="schools_school__eef8c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="school",
            index=models.Index(
                fields=["latitude", "longitude"], name="schools_latitud_b47079_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="school",
            index=models.Index(
                fields=["overall_rating"], name="schools_overall_97acad_idx"
            ),
        ),
    ]
